apiVersion: v1
kind: Service
metadata:
  name: super-mario-service
  namespace: super-mario
  labels:
    app: super-mario
spec:
  selector:
    app: super-mario
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
